# SPDX-FileCopyrightText: 2024 Baking Bad <hello@bakingbad.dev>
#
# SPDX-License-Identifier: MIT

version: '3.8'

services:
  observer-node:
    image: ztepler/ghostnet-observer
    environment:
      - WASM_GHOSTNET_SNAPSHOT=https://snapshots.eu.tzinit.org/etherlink-ghostnet/wasm-ghostnet.tar.gz
      - ETH_GHOSTNET_SNAPSHOT=https://snapshots.eu.tzinit.org/etherlink-ghostnet/eth-ghostnet.archive
      - OCTEZ_RPC_NODE=https://rpc.tzkt.io/ghostnet
      - ROLLUP_ADDRESS=sr18wx6ezkeRjt1SZSeZ2UQzQN3Uc3YLMLqg

